version: '3'
services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  express:
    build: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mysql

  nextjs:
    build: ./frontend
    ports:
      - '3000:3000'

volumes:
  mysql_data:
